apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            # Monta nginx.conf no local correto
            - name: frontend-files
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            # Monta arquivos estáticos
            - name: frontend-files
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            - name: frontend-files
              mountPath: /usr/share/nginx/html/js.js
              subPath: js.js
            - name: frontend-files
              mountPath: /usr/share/nginx/html/css.css
              subPath: css.css
      volumes:
        - name: frontend-files
          configMap:
            name: frontend-files-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
